### ISSUE TITLE
s4 command line to filter by filename

### ISSUE THREAD

**Issue by jkustan** [jtmoon79/super-speedy-syslog-searcher#163]
## Summary

Request that s4 command line be able to filter by filename, eg "s4 log/sidekiq*" or some other format to pick up only sidekiq log files.

### Current behavior

Right now s4 will recurse all files in a given folder but AFAIK there's no way to tell it to only pick up certain filename patterns.

### Suggested behavior

Since our log files are huge (hundreds of MB / GB+), even with log rotation it can take s4 a long time to crunch files. If I'm looking for something in our udp logfiles (/log/[aws_task_id]/udp_logger.log), I don't need it to crunch through a GB of rails logs. I'd like the ability to do this:

s4 log/udp*
or
s4 log/**/udp*
or
s4 log -filename_pattern=udp.*

or something like that, to limit the files it crunches to the ones I'm interested in, which will make it MUCH more performant if I know which logs I'm interested in.

Plan B is to change our logging code to put each log type in its own directory, but I was wondering how hard this would be to add to s4.

Thank you!

**Comment by jtmoon79** [comment]
This is intentionally outside the scope of `s4`. Use other programming methods and/or Unix tools to pass your preferred files (I suggest Unix tool `find`). You can also pass a listing of files via stdin and `-` signifier (e.g. `cat specific-logs.txt | s4 -`)
