### ISSUE TITLE
add filter option ala 'grep -E' 

### ISSUE THREAD

**Issue by geolaw** [jtmoon79/super-speedy-syslog-searcher#216]
## Summary

Would be great to be able to filter log items based on a regex

### Current behavior

s4 will merge all lines 

### Suggested behavior

Using the '-E' option like on grep, pass s4 a regex to filter the logs on

Describe the feature change.

s4 -E 'one|two|three|four' log1 log2 log3 > merged

Will only result in lines from log1, log2 and log3 container 'one' 'two' 'three' or 'four' 

### Other

I was planning on just post processing the output with a pipe to grep -E, but then I realized with the other RFE that I submitted (https://github.com/jtmoon79/super-speedy-syslog-searcher/issues/215) that ideally a RFE to build this right into s4 would be more ideal

**Comment by geolaw** [comment]
RTFM :) 

Maybe its possible to do this via stdin? 

the --help shows : 
~~~
Arguments:
  <PATHS>...  Path(s) of log files or directories.
              Directories will be recursed. Symlinks will be followed.
              Paths may also be passed via STDIN, one per line. The user must
              supply argument "-" to signify PATHS are available from STDIN.
~~~

So if I wanted to grep -E 'one|two|three|four' on a series of input files (e.g. /path/to/log1 /path/to/log2 /path/to/log3)  and then pass that onto s4 what would the syntax be?

**Comment by jtmoon79** [comment]
Thanks for the suggestion @geolaw and the write-up with an example. That really helps  :-)

> Using the '-E' option like on grep, pass s4 a regex to filter the logs on

This is where process Piping should be used.
While I _could_ add a grep-like `-E` filtering, there is already implementations of `grep` (or `Select-String` in PowerShell) that will work just as well.
Additionally, while it might _seem_ like building in the regular expression into `s4` would be fast, I'm fairly certain it won't be.  Simply, Unix from the start has a very fast process pipelining capability. And [GNU grep](https://www.gnu.org/software/grep/manual/html_node/index.html) (and [BSD grep](https://man.openbsd.org/grep)) are extremely fast. Whatever I write, wouldn't be much better than piping to those trusty old `grep` programs.
It wouldn't surprise me if my implementation was slower; I'm using [Rust regex library](https://docs.rs/regex/latest/regex/) which is relatively new (and slow) compared to GNU `grep` (or BSD `grep`) which has been optimized over decades by many people (it's _really_ fast).

> So if I wanted to grep -E 'one|two|three|four' on a series of input files (e.g. /path/to/log1 /path/to/log2 /path/to/log3) and then pass that onto s4 what would the syntax be?

I think what you want is to pipe data from `s4` to `grep`? Yes, you can pass a file listing via stdin (one path per line) or on the command-line and then pipe to `grep`, e.g.

```
$ s4 log1 log2 log3 | grep -E 'one|two|three|four' > merged
```
or
```
$ echo "log1
log2
log3" | s4 - | grep -E 'one|two|three|four' > merged
```
